modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/cech12/BrickFurnace/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="brickfurnace"
    version="${file.jarVersion}"
    displayName="Brick Furnace"
    displayURL="https://github.com/cech12/BrickFurnace"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds Brick Furnaces.
    '''
[[dependencies.brickfurnace]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brickfurnace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brickfurnace]]
   modId="jei"
   mandatory=false
   versionRange="[15.0.0.17,)"
   referralUrl="https://github.com/mezz/JustEnoughItems"
   ordering="NONE"
   side="BOTH"
[[dependencies.brickfurnace]]
   modId="theoneprobe"
   mandatory=false
   versionRange="[1.20.0-9.0.0,)"
   referralUrl="https://www.curseforge.com/minecraft/mc-mods/the-one-probe"
   ordering="NONE"
   side="BOTH"
[[dependencies.brickfurnace]]
   modId="immersiveengineering"
   mandatory=false
   versionRange="[1.19.4-9.4.0,)"
   referralUrl="https://github.com/BluSunrize/ImmersiveEngineering"
   ordering="NONE"
   side="BOTH"