modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/cech12/BrickShears/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="brickfurnace"
    version="${file.jarVersion}"
    displayName="Brick Furnace"
    displayURL="https://github.com/cech12/BrickFurnace"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds Brick Furnaces.
    '''
[[dependencies.brickfurnace]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,37)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brickfurnace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brickfurnace]]
   modId="jei"
   mandatory=false
   versionRange="[7.7.1.115,)"
   ordering="NONE"
   side="BOTH"