modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/cech12/BrickFurnace/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="brickfurnace"
    version="${file.jarVersion}"
    displayName="Brick Furnace"
    displayURL="https://github.com/cech12/BrickFurnace"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds Brick Furnaces.
    '''
[[dependencies.brickfurnace]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brickfurnace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brickfurnace]]
   modId="jei"
   mandatory=false
   versionRange="[11.9999,)"
   referralUrl="https://github.com/mezz/JustEnoughItems"
   ordering="NONE"
   side="BOTH"
[[dependencies.brickfurnace]]
   modId="theoneprobe"
   mandatory=false
   versionRange="[1.19.3-7.0.0,)"
   referralUrl="https://www.curseforge.com/minecraft/mc-mods/the-one-probe"
   ordering="NONE"
   side="BOTH"
[[dependencies.brickfurnace]]
   modId="immersiveengineering"
   mandatory=false
   versionRange="[1.19.3-9.2.0,)"
   referralUrl="https://github.com/BluSunrize/ImmersiveEngineering"
   ordering="NONE"
   side="BOTH"